# Generated by Django 5.0.1 on 2024-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='orginization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='shaxs_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
